modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="longer-sausage"
description='''
CreateGo Mod
'''

[[mixins]]
config="creatego.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dynamicdimensions"
type="required"
versionRange="[0.9.1,0.10)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="modernui"
type="required"
versionRange="[3.13.0.1,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="create"
type="optional"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="required"
versionRange="[2.0.3,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create_aeronautics_toolgun"
type="required"
versionRange="[0.3.2,0.4)"
ordering="AFTER"
side="BOTH"
